export type ServiceCategory =
  | "Advisory & Assessment"
  | "Transactional AI & Bid"
  | "High-Stakes Human & Legal"
  | "SaaS & Partner";

export interface Service {
  id: string;
  name: string;
  category: ServiceCategory;
  price: number;
  floor: number;
  ai_cost: number;
  manual_cost: number;
  displacement?: number;
  period?: "month" | "year";
  iso_clause: string;
  desc: string;
  hil: boolean; // human-in-the-loop
  plain?: string;   // plain-language explanation for non-specialists
  example?: string; // concrete example scenario
  suggests?: string[]; // IDs of complementary services to cross-sell
}

export const services: Service[] = [
  // Category 1: Advisory & Assessment
  { id: "compliance-baseline", name: "Compliance Baseline Assessment (SVC-001)", category: "Advisory & Assessment", price: 999, floor: 800, ai_cost: 0.5, manual_cost: 4680, displacement: 0.829, iso_clause: "ISO 9001 Clause 8.2", desc: "Establishes the client's compliance posture at T0 against a named regulatory set, creating the baseline BKR record.", hil: true, plain: "A one-off health check that shows where you stand today against the rules that apply to you, so every future bid starts from a known baseline.", example: "You're a 40-person facilities firm considering NHS work. This tells you 'you're 62% ready — missing DSPT and a current CRP' before you spend a penny on a real bid.", suggests: ["gap-analysis", "iso-readiness"] },
  { id: "regulatory-impact", name: "Regulatory Change Assessment (SVC-002)", category: "Advisory & Assessment", price: 499, floor: 300, ai_cost: 0.5, manual_cost: 1032.5, displacement: 0.709, iso_clause: "ISO 37301 Clause 4.1", desc: "Assesses the client impact of a named regulatory change (delta T0→T1) on their bid readiness.", hil: true, plain: "When a new law or procurement rule lands, this tells you specifically what it means for your bid pipeline — not a generic newsletter.", example: "The Procurement Act 2023 goes live. We tell you which of your 12 live opportunities now need extra evidence and what to change first.", suggests: ["gap-analysis", "compliance-diary"] },
  { id: "gap-analysis", name: "Gap Analysis & Remediation (SVC-003)", category: "Advisory & Assessment", price: 799, floor: 500, ai_cost: 0.5, manual_cost: 2400, displacement: 0.792, iso_clause: "ISO 22301 Clause 8.4", desc: "Prioritised, step-by-step remediation plan against an established baseline.", hil: true, plain: "After the baseline, this is the fix-it plan: what to do first, second and third, with owners and effort estimates.", example: "Baseline showed you're missing 6 things. Gap Analysis ranks them: 'ISO 27001 first (blocks 8 tenders), CRP second (blocks 3), staff training third'.", suggests: ["compliance-baseline", "evidence-vault"] },
  { id: "evidence-mapping", name: "Evidence Mapping & BKR Setup (SVC-004)", category: "Advisory & Assessment", price: 99, floor: 0, ai_cost: 0.2, manual_cost: 178.14, displacement: 0.444, iso_clause: "ISO 55001 Clause 7.5", desc: "AI extracts bid requirements and maps them to certificates, policies, CVs in the BKR in 5 minutes.", hil: false, plain: "Upload a tender and your document folder — AI matches every 'must provide' requirement to the exact file you already have (or flags what's missing).", example: "A 90-page ITT asks for 27 pieces of evidence. In 5 minutes you get a table showing which 21 you already have and the 6 gaps to fix.", suggests: ["ai-bid-draft", "evidence-vault"] },
  { id: "iso-readiness", name: "ISO Readiness Assessment (SVC-005)", category: "Advisory & Assessment", price: 1999, floor: 1500, ai_cost: 1, manual_cost: 6500, displacement: 0.769, iso_clause: "ISO 27001 Clause 9.2", desc: "Client readiness against ISO 27001 / 9001 / 14001 with a pre-audit gap map.", hil: true, plain: "A pre-audit rehearsal before you pay a certification body — tells you exactly what your real auditor will fail you on.", example: "You've booked a Stage 1 ISO 27001 audit in 8 weeks. We find the 4 controls that would fail and give you time to fix them at a fraction of a re-audit fee.", suggests: ["gap-analysis", "compliance-diary"] },

  // Category 2: Transactional AI & Bid
  { id: "ai-win-theme", name: "AI Win-Theme Generator (SVC-010)", category: "Transactional AI & Bid", price: 99, floor: 0, ai_cost: 0.3, manual_cost: 205.95, displacement: 0.52, iso_clause: "ISO/IEC 42001 Clause 6.1", desc: "AI analyses criteria and competitor strengths to generate 3-5 persuasive angles for your bid draft.", hil: false, plain: "The 'why us, not them' angles for your bid — the 3–5 messages every answer should reinforce.", example: "For a school catering tender, it may return: (1) 100% local supply, (2) real-time allergen tracking, (3) 40% cheaper Scope 3 emissions than incumbent.", suggests: ["ai-bid-draft", "ai-bid-review"] },
  { id: "ai-bid-draft", name: "AI Bid Draft (SVC-011)", category: "Transactional AI & Bid", price: 199, floor: 0, ai_cost: 1.5, manual_cost: 752.5, displacement: 0.98, iso_clause: "ISO/IEC 42001 Clause 8.2", desc: "Generates complete compliant bid answers aligned to win themes in 20 minutes instead of 10 hours.", hil: false, plain: "The first-draft writing done for you — every question in the tender answered in your voice, in 20 minutes.", example: "A 40-question SQ that normally eats a full weekend comes back in 20 minutes, ready for you to fact-check and personalise.", suggests: ["ai-bid-review", "premium-red-team", "evidence-mapping"] },
  { id: "pqq-first-draft", name: "PQQ First Draft + Human Review", category: "Transactional AI & Bid", price: 149, floor: 75.25, ai_cost: 0.5, manual_cost: 301, displacement: 0.769, iso_clause: "ISO 9001 Clause 8.5", desc: "AI drafts SQ/PQQ responses instantly, plus a 1-hour professional bounty-board review (48h SLA).", hil: true, plain: "AI writes the PQQ; a qualified bid writer then spends an hour cleaning it up. Back within 48 hours.", example: "You're shortlisted for a council framework and the PQQ is due Friday. Submit Monday, human-reviewed draft by Wednesday.", suggests: ["ai-bid-draft", "pqq-surgery"] },
  { id: "crp-generator", name: "CRP Generator (PPN 06/21)", category: "Transactional AI & Bid", price: 129, floor: 0, ai_cost: 0.4, manual_cost: 1200, iso_clause: "ISO 14001 Clause 8.1", desc: "12-question survey calculates Scope 1/2/3 emissions and outputs a fully compliant Carbon Reduction Plan.", hil: false, plain: "A Carbon Reduction Plan — required by PPN 06/21 for any public contract over £5m — generated from a 12-question form.", example: "Answer 12 questions about fleet, offices and suppliers; get back a signed-off, PPN-compliant CRP PDF you can attach to the tender.", suggests: ["social-value-narrative", "compliance-diary"] },
  { id: "social-value-narrative", name: "Social Value Narrative (PPN 06/20)", category: "Transactional AI & Bid", price: 99, floor: 0, ai_cost: 0.3, manual_cost: 263.38, iso_clause: "ISO 14001 Clause 4.3", desc: "Localised, TOMs-compliant Social Value commitments with explicit KPIs for PPN 06/20.", hil: false, plain: "The 'social value' section (usually 10% of the score) written with real, local, measurable commitments — not vague promises.", example: "For a Manchester contract: '3 apprenticeships at Trafford College, 240 volunteer hours at Wood Street Mission, £8k local SME spend'.", suggests: ["crp-generator", "ai-bid-draft"] },
  { id: "ai-tender-response", name: "AI Tender Response (Full ITT)", category: "Transactional AI & Bid", price: 399, floor: 0, ai_cost: 0.2, manual_cost: 937.5, displacement: 0.992, iso_clause: "ISO/IEC 42001 Clause 8.3", desc: "End-to-end ITT writing: compliance matrices, evidence annexes, technical narratives.", hil: false, plain: "The full end-to-end bid package: compliance matrix, evidence annexes, method statements — everything an ITT asks for.", example: "A 200-page ITT with 6 lots and 34 questions comes back as a complete, submission-ready pack in a single working day.", suggests: ["ai-bid-review", "premium-red-team"] },
  { id: "ai-bid-review", name: "AI Bid Review & Scoring", category: "Transactional AI & Bid", price: 249, floor: 0, ai_cost: 0.14, manual_cost: 328, displacement: 0.99, iso_clause: "ISO/IEC 42001 Clause 9.2", desc: "Simulates evaluator marking against award criteria and returns prioritised fixes across 2 cycles.", hil: false, plain: "AI reads your draft the way the buyer's evaluators will, scores it, and tells you which answers to fix first to lift the score most.", example: "Your draft scores 68/100. The review says 'answer 7 is losing you 9 marks — here's why' — you rewrite, rescore, submit at 84.", suggests: ["ai-bid-draft", "premium-red-team"] },
  { id: "ai-win-loss", name: "AI Win/Loss Analysis", category: "Transactional AI & Bid", price: 149, floor: 0, ai_cost: 0.14, manual_cost: 246, displacement: 0.985, iso_clause: "ISO/IEC 42001 Clause 10.1", desc: "Turns tender feedback into root-cause rejections and remediation playbooks for the BKR.", hil: false, plain: "You lost. This turns the buyer's feedback letter into 'here's why, and here's exactly what to change on the next one'.", example: "Feedback says 'weak on social value'. Analysis pinpoints the two paragraphs, shows the winning bidder's likely pattern, and prescribes a fix.", suggests: ["social-value-narrative", "ai-bid-draft"] },
  { id: "private-rfp-response", name: "Private-Sector RFP Response", category: "Transactional AI & Bid", price: 499, floor: 0, ai_cost: 1.5, manual_cost: 602, displacement: 0.98, iso_clause: "ISO 9001 Clause 8.2.3", desc: "AI-generated RFP response optimised for private-sector buyers.", hil: false, plain: "Same as an ITT response, tuned for corporate buyers — commercial, benefits-led writing, not public-sector compliance-speak.", example: "A FTSE 250 buyer sends an RFP; we return a commercially framed response with ROI narrative and pricing options.", suggests: ["ai-bid-review", "premium-red-team"] },

  // Category 3: High-Stakes Human & Legal
  { id: "tupe-risk-assessment", name: "TUPE Risk Assessment", category: "High-Stakes Human & Legal", price: 179, floor: 0, ai_cost: 0.5, manual_cost: 375, displacement: 0.987, iso_clause: "ISO 45001 Clause 6.1.2", desc: "AI screens TUPE applicability, extracts ELI schedules, and risk-scores transfer liabilities.", hil: false, plain: "TUPE = you may inherit staff from the outgoing supplier. This tells you whether it applies here, how many people, and what it will cost you.", example: "A cleaning contract shows 22 staff on £11.50/h with 3 on long-term sick. Assessment flags £84k of hidden annual cost the tender price didn't warn about.", suggests: ["pqq-surgery", "disqualification-defence"] },
  { id: "standstill-interception-brief", name: "Standstill Interception Brief", category: "High-Stakes Human & Legal", price: 499, floor: 0, ai_cost: 0.5, manual_cost: 1032.5, displacement: 0.99, iso_clause: "ISO 37301 Clause 9.1", desc: "AI-driven scoring audit of bid rejections under s.51 PA23. Identifies procedural scoring breaches for challenge.", hil: false, plain: "You lost, and there's a 10-day standstill window to challenge. This tells you in 24 hours whether there are grounds to write to the buyer.", example: "You lost by 2 marks. Brief spots that the winner was scored on evidence that wasn't in the criteria — a procedural breach worth challenging.", suggests: ["disqualification-defence", "ai-win-loss"] },
  { id: "premium-red-team", name: "Premium Red Team Review", category: "High-Stakes Human & Legal", price: 1299, floor: 812.5, ai_cost: 0, manual_cost: 812.5, displacement: 0, iso_clause: "ISO 9001 Clause 8.6", desc: "Guaranteed 6.5h review by a certified APMP Practitioner. Floor fully protected.", hil: true, plain: "A senior bid writer (APMP Practitioner) tears your draft apart for 6.5 hours as if they were the evaluator. Fully human, guaranteed.", example: "Before submitting a £2m NHS bid, a certified reviewer rewrites your three weakest answers and confirms your compliance matrix.", suggests: ["ai-bid-draft", "ai-bid-review"] },
  { id: "disqualification-defence", name: "Disqualification Defence Pack", category: "High-Stakes Human & Legal", price: 2499, floor: 1475, ai_cost: 0.5, manual_cost: 1475, displacement: 0, iso_clause: "ISO 37001 Clause 9.1", desc: "Legal challenge package. Solicitor reviews AI case files on s.57–64 PA23 breaches and issues formal letter.", hil: true, plain: "You were excluded from a tender. A solicitor uses AI-prepared case files to challenge it under s.57–64 of the Procurement Act 2023.", example: "You were disqualified for a 'past misconduct' finding. Defence pack shows the finding was misapplied and drafts the formal challenge letter.", suggests: ["standstill-interception-brief"] },
  { id: "pqq-surgery", name: "PQQ Surgery", category: "High-Stakes Human & Legal", price: 399, floor: 312.5, ai_cost: 0, manual_cost: 312.5, displacement: 0, iso_clause: "ISO 45001 Clause 8.1", desc: "Interactive 90-minute live screen share with an APMP Practitioner on high-risk TUPE and ISO clauses.", hil: true, plain: "90 minutes on Zoom, screen-shared, with a senior bid consultant to work through the hardest questions in your PQQ live.", example: "You're stuck on TUPE, insurance limits and an ISO 27001 gap. In 90 minutes you leave with defensible answers to all three.", suggests: ["pqq-first-draft", "tupe-risk-assessment"] },
  { id: "framework-t1", name: "Framework Support T1 (Simple)", category: "High-Stakes Human & Legal", price: 999, floor: 0, ai_cost: 0.5, manual_cost: 1000, displacement: 0.99, iso_clause: "ISO/IEC 42001 Clause 8.4", desc: "AI-only framework support (G-Cloud) for evidence mapping and automated bid compilation.", hil: false, plain: "AI-only help for straightforward framework applications like G-Cloud — mapping evidence and generating your submission.", example: "You're applying to G-Cloud 14 for the first time. AI pulls together your service definitions, pricing matrix and case studies.", suggests: ["evidence-mapping", "framework-t2"] },
  { id: "framework-t2", name: "Framework Support T2 (Standard)", category: "High-Stakes Human & Legal", price: 1999, floor: 301, ai_cost: 0.5, manual_cost: 2000, displacement: 0.95, iso_clause: "ISO 9001 Clause 8.4", desc: "AI framework support plus 4 hours of professional human writer review on standard CCS applications.", hil: true, plain: "Same as T1 but with 4 hours of a professional writer on top, for standard CCS-style frameworks.", example: "CCS Management Consultancy Framework — AI drafts, then a bid writer rewrites your strategic-outcomes narrative.", suggests: ["framework-t3", "premium-red-team"] },
  { id: "framework-t3", name: "Framework Support T3 (Complex)", category: "High-Stakes Human & Legal", price: 2999, floor: 601, ai_cost: 0.5, manual_cost: 3000, displacement: 0.9, iso_clause: "ISO 9001 Clause 8.4.2", desc: "T2 plus 1.5 hours of senior consultant strategy on complex multi-lot NHS frameworks.", hil: true, plain: "T2 plus 90 minutes of senior consulting for genuinely complex frameworks — multi-lot NHS, MoD or DfE work.", example: "NHS SBS multi-lot clinical framework: senior consultant helps you decide which lots to bid and shapes the win theme per lot.", suggests: ["enterprise-strategic-transformation"] },
  { id: "enterprise-strategic-transformation", name: "Enterprise Strategic Transformation", category: "High-Stakes Human & Legal", price: 12999, floor: 8000, ai_cost: 500, manual_cost: 12999, displacement: 0.667, iso_clause: "ISO 44001 Clause 8.2", desc: "Direct Glaxton killer. 4–6 weeks AI processing plus 2 senior consultants (20h each) delivering full readiness registers.", hil: true, plain: "A 4–6 week programme with two senior consultants to make an established business genuinely enterprise-tender ready.", example: "A £15m turnover firm wants onto strategic NHS/MoD frameworks — this delivers the compliance registers, ISO alignment and bid infrastructure.", suggests: ["enterprise-readiness-accelerator", "iso-readiness"] },
  { id: "enterprise-readiness-accelerator", name: "SME Enterprise Readiness Accelerator", category: "High-Stakes Human & Legal", price: 2499, floor: 1000, ai_cost: 100, manual_cost: 2499, displacement: 0.75, iso_clause: "ISO 37301 Clause 8.2", desc: "SME on-ramp. AI compliance mapping, PPN 06/21 CRP, plus 5 hours of APMP strategist workshop.", hil: true, plain: "The SME-scale on-ramp: compliance mapped, CRP written, plus a 5-hour workshop with an APMP strategist to plan your bid pipeline.", example: "A 25-person SaaS firm wants to break into public sector. In 2 weeks you have a CRP, an ISO gap plan and a target list of 8 realistic tenders.", suggests: ["compliance-baseline", "framework-t1"] },

  // Category 4: SaaS & Partner
  { id: "compliance-diary", name: "Compliance Diary Subscription", category: "SaaS & Partner", price: 49, floor: 0, ai_cost: 0.05, manual_cost: 49, displacement: 1, period: "month", iso_clause: "ISO 37301 Clause 6.1", desc: "Tracks certificate expirations with automated notifications. Pairs with Compliance Currency Score.", hil: false, plain: "A calendar that watches your certificates and insurance for you and warns you 60 days before anything expires.", example: "Your ISO 9001 lapses on 4 March. On 3 January you get an email: 're-book your surveillance audit now or you'll fail 6 open tenders'.", suggests: ["evidence-vault", "iso-readiness"] },
  { id: "evidence-vault", name: "Evidence Vault Subscription", category: "SaaS & Partner", price: 29, floor: 0, ai_cost: 0.03, manual_cost: 29, displacement: 1, period: "month", iso_clause: "ISO 27001 Annex A.8.24", desc: "Client-side encrypted cloud storage via Web Crypto AES-GCM. Key never leaves browser.", hil: false, plain: "A secure vault for your bid evidence (certificates, policies, CVs, case studies) — encrypted in your browser so even we can't read it.", example: "Every certificate, insurance doc and case study lives in one place, tagged and instantly attachable when a tender asks for it.", suggests: ["evidence-mapping", "compliance-diary"] },
  { id: "bid-library", name: "Bid Library Subscription", category: "SaaS & Partner", price: 99, floor: 0, ai_cost: 1.7, manual_cost: 99, displacement: 1, period: "month", iso_clause: "ISO 55001 Clause 4.1", desc: "AI-tagged bid content repository. Replaces Loopio at 96% cheaper.", hil: false, plain: "Every answer you've ever written, tagged by topic and reusable. AI finds and adapts the right paragraph for each new tender.", example: "New tender asks about cyber-incident response. Library pulls the answer from your Sept 2025 MoJ bid and adapts it in seconds.", suggests: ["ai-bid-draft", "evidence-vault"] },
  { id: "psl-partner-seat", name: "PSL Partner Seat", category: "SaaS & Partner", price: 499, floor: 0, ai_cost: 50, manual_cost: 499, displacement: 1, period: "month", iso_clause: "ISO 44001 Clause 6.1", desc: "Monthly licence per seat for bid consultancies. Floor set to £0 to prevent owner-margin drainage.", hil: false, plain: "A per-seat monthly licence for a bid consultancy or reseller to work inside BidSense for their own clients.", example: "A 5-person bid consultancy pays for 5 seats and delivers all their client work through BidSense at their own hourly rate.", suggests: ["psl-enterprise-partner-c2"] },
  { id: "psl-enterprise-partner-c2", name: "PSL Enterprise Partner (C2)", category: "SaaS & Partner", price: 4999, floor: 1500, ai_cost: 200, manual_cost: 4999, displacement: 0.5, period: "month", iso_clause: "ISO 44001 Clause 10.1", desc: "C2 partner tier. Unlimited seats, named partner manager, 10% VDC referral split, reselling rights.", hil: true, plain: "The enterprise partner tier: unlimited seats, a named partner manager, and the right to resell BidSense with a 10% referral split.", example: "A 40-person national bid consultancy runs their whole practice on BidSense and earns commission on every client they refer.", suggests: ["psl-white-label-reseller-c3"] },
  // FIXED: price was 1000 with period "year" while the desc promised "£12,000/year" — a 12x
  // internal contradiction (the £1,000/250/41.6 figures look like unannualised monthly inputs
  // left in the price/floor/ai_cost fields). Scaled ×12 to match the stated annual price and
  // preserve the original floor/AI-cost/margin ratios. Confirm the £12,000 anchor against a
  // real PSL conversation before this goes live — it was never independently re-verified.
  { id: "psl-white-label-reseller-c3", name: "PSL White-Label Reseller (C3)", category: "SaaS & Partner", price: 12000, floor: 3000, ai_cost: 499.2, manual_cost: 12000, displacement: 0.75, period: "year", iso_clause: "ISO 44001 Clause 10.3", desc: "C3 white-label license (£12,000/year). Permits reselling to their own SME base.", hil: true, plain: "An annual white-label licence — rebrand BidSense as your own platform and resell it to your SME client base.", example: "A regional bid agency launches 'AcmeBids' powered by BidSense, keeps 100% of client-facing branding, and sells it as their own SaaS.", suggests: ["psl-enterprise-partner-c2"] },
];

export const categories: ServiceCategory[] = [
  "Advisory & Assessment",
  "Transactional AI & Bid",
  "High-Stakes Human & Legal",
  "SaaS & Partner",
];

export function findService(id: string) {
  return services.find((s) => s.id === id);
}
